export enum LoginActionTypes {
  SEND_LOGIN_REQ = "SEND_LOGIN_REQ",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILED = "LOGIN_FAILED",
}
export enum MenuActionTypes {
  SEND_MENU_REQ = "SEND_MENU_REQ",
  MENU_SUCCESS = "MENU_SUCCESS",
  MENU_FAILED = "MENU_FAILED",
}
export enum UsersListActionTypes {
  SEND_USERS_LIST_REQ = "SEND_USERS_LIST_REQ",
  USERS_LIST_SUCCESS = "USERS_LIST_SUCCESS",
  USERS_LIST_FAILED = "USERS_LIST_FAILED",
}
export enum AdminsListActionTypes {
  SEND_ADMINS_LIST_REQ = "SEND_ADMINS_LIST_REQ",
  ADMINS_LIST_SUCCESS = "ADMINS_LIST_SUCCESS",
  ADMINS_LIST_FAILED = "ADMINS_LIST_FAILED",
}
export enum rolDefineActionTypes {
  SEND_ROL_DEFINE_REQ = "SEND_ROL_DEFINE_REQ",
  ROL_DEFINE_SUCCESS = "ROL_DEFINE_SUCCESS",
  ROL_DEFINE_FAILED = "ROL_DEFINE_FAILED",
}

